import os
from supabase import create_client, Client
from dotenv import load_dotenv

# .env.local 파일에서 환경 변수를 로드합니다.
# Next.js 프로젝트와 환경 변수를 공유하기 위함입니다.
load_dotenv(dotenv_path='.env.local')

# --- Supabase 클라이언트 초기화 ---
url: str = os.environ.get("NEXT_PUBLIC_SUPABASE_URL")
key: str = os.environ.get("NEXT_PUBLIC_SUPABASE_ANON_KEY")

supabase: Client = None
is_supabase_connected = False

if url and key:
    try:
        supabase = create_client(url, key)
        is_supabase_connected = True
        print("Supabase client created successfully.")
    except Exception as e:
        print(f"Failed to create Supabase client: {e}")
        print("Training logs will not be saved to Supabase.")
else:
    print("Supabase URL or Key not found in .env.local. Training logs will not be saved.")
    print("Please set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY.")

def get_supabase_client():
    """Supabase 클라이언트 인스턴스를 반환합니다."""
    return supabase

def is_connected():
    """Supabase 연결 상태를 반환합니다."""
    return is_supabase_connected

# --- 예시 SQL (Supabase 대시보드에서 실행) ---
# CREATE TABLE training_logs (
#   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
#   created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
#   model_id UUID, -- 'pinn_models' 테이블의 id와 연결 (옵션)
#   epoch INT,
#   total_loss FLOAT,
#   boundary_loss FLOAT,
#   physics_loss FLOAT,
#   status TEXT DEFAULT 'in_progress'::text, -- e.g., 'in_progress', 'completed', 'diverged'
#   training_config JSONB
# );
# 
# -- model_id에 대한 외래 키 제약 조건 추가 (pinn_models 테이블이 있는 경우)
# -- ALTER TABLE training_logs ADD CONSTRAINT fk_model_id FOREIGN KEY (model_id) REFERENCES pinn_models(id);
